apiVersion: apps/v1
kind: Deployment
metadata:
  name: july
  labels:
    app: july
spec:
  replicas: 1
  selector:
    matchLabels:
      app: july
  template:
    metadata:
      labels:
        app: july
    spec:
      containers:
      - name: july
        image: vasyahuyasa/july:0.0.4
        ports:
        - containerPort: 80
        volumeMounts:
        - name: google-credentials
          mountPath: "/app/google"
        env:
        - name: STORAGE_DRIVER
          value: "gdrive"
        - name: CATALOG_ROOT
          value: "root"
        - name: GOOGLE_CREDENTIALS_PATH
          value: "google/credentials.json"
        - name: GOOGLE_TOKEN_PATH
          value: "google/token.json"
      volumes:
      - name: google-credentials
        secret:
          secretName: july-google-secret

---
apiVersion: v1
kind: Service
metadata:
  name: july
  labels:
    run: july
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: july

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: july-ingress
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: july
            servicePort: 80