apiVersion: v1
kind: Namespace
metadata:
  name: july

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: july-deployment
  labels:
    app: july
spec:
  replicas: 1
  selector:
    matchLabels:
      app: july
  template:
    metadata:
      labels:
        app: july
    spec:
      containers:
      - name: july
        image: docker.pkg.github.com/vasyahuyasa/july/july:v.0.0.3
        ports:
        - containerPort: 80
