name: Publish docker image

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build and publish to docker registry
      run: |
        PROJECT_NAME=`echo ${{ github.repository }} | sed 's/\(.*\)\///'`
        TAG=docker.pkg.github.com/${{ github.repository }}/${PROJECT_NAME}:latest
        echo ${TAG}
        docker login docker.pkg.github.com -u vasyahuyasa -p ${{ secrets.GITHUB_TOKEN }}
        docker build . -t ${TAG}
        docker push ${TAG}